-- Arky Finances - Supabase/Postgres bootstrap
-- Run this in Supabase SQL Editor for the database used by the FastAPI backend.
-- It creates the tables expected by the app and inserts only the minimum seed data.

create table if not exists public.users (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  locale varchar(20) not null default 'en-US',
  timezone varchar(64) not null default 'America/Argentina/Buenos_Aires',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.profiles (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  current_balance numeric(14, 2) not null default 0,
  minimum_cash_buffer numeric(14, 2) not null default 0,
  base_currency varchar(3) not null default 'ARS',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.incomes (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(120) not null,
  amount numeric(14, 2) not null,
  currency varchar(3) not null default 'ARS',
  start_date date not null,
  recurrence varchar(24) not null default 'monthly',
  is_salary_adjusted boolean not null default false,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.expenses (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(120) not null,
  category varchar(80) not null,
  amount numeric(14, 2) not null,
  currency varchar(3) not null default 'ARS',
  expense_type varchar(24) not null default 'fixed',
  recurrence varchar(24) not null default 'monthly',
  start_date date not null,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.goals (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(120) not null,
  target_amount numeric(14, 2) not null,
  currency varchar(3) not null default 'ARS',
  target_date date not null,
  priority integer not null default 2,
  monthly_contribution_ideal numeric(14, 2) not null default 0,
  current_progress numeric(14, 2) not null default 0,
  future_probability numeric(5, 2),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.scenarios (
  id integer generated by default as identity primary key,
  name varchar(80) not null,
  slug varchar(40) not null unique,
  description text not null,
  inflation_monthly numeric(6, 4) not null default 0,
  salary_adjustment_rate numeric(6, 4) not null default 0,
  salary_adjustment_frequency_months integer not null default 3,
  exchange_rate_variation_monthly numeric(6, 4) not null default 0,
  investment_return_monthly numeric(6, 4) not null default 0,
  unexpected_expense_amount numeric(14, 2) not null default 0,
  target_savings_rate numeric(6, 4) not null default 0,
  is_preset boolean not null default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists ix_profiles_user_id on public.profiles(user_id);
create index if not exists ix_incomes_user_id on public.incomes(user_id);
create index if not exists ix_expenses_user_id on public.expenses(user_id);
create index if not exists ix_goals_user_id on public.goals(user_id);
create index if not exists ix_scenarios_slug on public.scenarios(slug);

insert into public.users (name, locale, timezone)
select 'Primary user', 'en-US', 'America/Argentina/Buenos_Aires'
where not exists (select 1 from public.users);

insert into public.profiles (user_id, current_balance, minimum_cash_buffer, base_currency)
select users.id, 0, 0, 'ARS'
from public.users
where not exists (
  select 1
  from public.profiles
  where profiles.user_id = users.id
);

insert into public.scenarios (
  name,
  slug,
  description,
  inflation_monthly,
  salary_adjustment_rate,
  salary_adjustment_frequency_months,
  exchange_rate_variation_monthly,
  investment_return_monthly,
  unexpected_expense_amount,
  target_savings_rate,
  is_preset
)
values
  (
    'Conservative',
    'conservative',
    'Higher inflation, lower returns, and a tighter savings posture.',
    0.0800,
    0.1200,
    4,
    0.0700,
    0.0100,
    120000.00,
    0.2200,
    true
  ),
  (
    'Base',
    'base',
    'Balanced assumptions for monthly planning and active savings goals.',
    0.0500,
    0.1000,
    4,
    0.0500,
    0.0180,
    80000.00,
    0.1800,
    true
  ),
  (
    'Optimistic',
    'optimistic',
    'Lower inflation, better returns, and lighter unexpected spending pressure.',
    0.0300,
    0.1200,
    3,
    0.0300,
    0.0250,
    40000.00,
    0.1600,
    true
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  inflation_monthly = excluded.inflation_monthly,
  salary_adjustment_rate = excluded.salary_adjustment_rate,
  salary_adjustment_frequency_months = excluded.salary_adjustment_frequency_months,
  exchange_rate_variation_monthly = excluded.exchange_rate_variation_monthly,
  investment_return_monthly = excluded.investment_return_monthly,
  unexpected_expense_amount = excluded.unexpected_expense_amount,
  target_savings_rate = excluded.target_savings_rate,
  is_preset = excluded.is_preset,
  updated_at = now();
